<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEexSc9S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEexSc9S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEexSc9S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEexSc9S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEexSc9S\App_KernelDevDebugContainer([
    'container.build_hash' => 'EexSc9S',
    'container.build_id' => '691ea4f2',
    'container.build_time' => 1653557494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEexSc9S');
